### ISSUE TITLE
Script download button does not work on Linux since 1.0.15

### ISSUE THREAD

**Issue by shyblower** [pinokiocomputer/pinokio#104]
On 1.0.15 and 1.0.16 the download button for scripts does not work any more on my Gentoo Linux.
I have to start 2.0.18 to download the script, then I can open 1.0.15 or 1.0.16 and click "install".

**Comment by sornen** [comment]
I also have this problem with the Appimage file. On 1.0.15/16 the download button for the scripts does not work.

**Comment by teddy0605** [comment]
Same issue here with both 1.0.15 and 1.0.16 appimage on fedora 39. Developer tools or bash do not show any error/failure, the button just does not work.

**Comment by wadael** [comment]
Same here. Downloaded appimage, made it executable.

Download buttons have no effect. 
I opened the dev tools, tried to open the url in ffox and file explorer with no success.

Example url
     pinokio://download?uri=https://github.com/cocktailpeanutlabs/magnet
     
The pinokio protocol seems to not be attached to a program

v1.0.16 on mint 21.2, krnl 6.5

**Comment by wadael** [comment]
solved in 1.1.0

Thank you

**Comment by shyblower** [comment]
Also solved for me in 1.1.0, ... closing
