### ISSUE TITLE
Running AppImage in Linux installs but loops without launching

### ISSUE THREAD

**Issue by gjdaley** [pinokiocomputer/pinokio#14]
Running the AppImage file in Linux prompts for the folder to install and runs through the install script. Once it completes (successfully), the button pops up to "Launch". Clicking the button restarts the install process. There is no way to actually launch the app...

**Comment by JeremyKPark** [comment]
I am also experiencing this unfortunate loop in Ubuntu 22.04. Looking forward to solving this so can get started!

**Comment by JeremyKPark** [comment]
This was resolved in the latest version, thanks again!

**Comment by gjdaley** [comment]
I also confirm that this issue is resolved.
