### ISSUE TITLE
The app does scary stuff in the background - Users should be very very sceptical with this repo!

### ISSUE THREAD

**Issue by knixx-fm** [pinokiocomputer/pinokio#153]
I just installed this app and it eats up almost all my CPU while the UI states, that it's doing nothing. And it is doing it in some kind of circle.

I looked at your discord and learned that other users experienced the same, for quite some time now. Your fans claim it's got something to do with the stdout.txt. Somebody else said, that this is not true. - I looked at that file. And guess what, it's not the case.

**Whatever the scripts are doing in the background, it is not trustworthy.**

**Comment by cbxk1xg** [comment]
Same here. It froze my test PC. Looks like a crypto miner or something else. It's most def not a clean tool.

**Comment by westNeighbor** [comment]
When I saw the installation requirements, I just deleted pinokio, it is scary cause many already in my system but it requires to fresh installation.

**Comment by cbxk1xg** [comment]
I reported the repo. I tried to reach the author, but I guess he's busy counting bitcoins.

**Comment by cbxk1xg** [comment]
That's the thing with malware. You just put it out and wait.

**Comment by cocktailpeanut** [comment]
hey guys, i'm the creator. first of all, the thing that runs in the background is a logging system (which logs the system status to your local file, which can be used for debugging). Note that this does not use any network which means it's only for your own usage and not sent anywhere. It's literally for your own good when trying to figure out why something is not working.

The intent was to have the most up to date system information.

But I can see the drawback here and will address this in the next immediate release, probably take out the constant systeminfo logging and only do it when explicitly requested. Sorry about that.

> The vendor released 10 new version in the last 4 (!) days!

This is a valid point and was a total mistake. I usually publish intermediate releases to my own repo and only publish to this repository when it's ready for production, but this time I made a mistake and kept publishing to this repo during the dev process. Will not be doing that going forward, only major stable releases will be published here.

Lastly, there's no bitcoin miner or whatever going on here. Everything is open source so you can check what is actually happening in the background in the source. For reference, here's how the repo works:

The `pinokiocomputer/pinokio` repo is an electron distribution that wraps the core engine, which you can find at `pinokiocomputer/pinokiod`. 99% of the logic is there, so you can check out that repo for the actual code. Hope this helps.

**Comment by blubbsy** [comment]
i saw this few days ago and wanted to comment on it and now @cocktailpeanut did it on its own. Wanted to so say exactly this:

> Lastly, there's no bitcoin miner or whatever going on here. Everything is open source so you can check what is actually happening in the background in the source. For reference, here's how the repo works:

i think this can be closed.
