### ISSUE TITLE
CUDA not installed (Bug)

### ISSUE THREAD

**Issue by Tipez** [pinokiocomputer/pinokio#154]
Pinokio 1.2.49

System: Linux Ubuntu 22.04 x86_64 

Trying to install dependencies
![image](https://github.com/pinokiocomputer/pinokio/assets/36464019/75a35e5b-907f-4841-8dd7-52df3c938fa5)

error :
`<<PINOKIO SHELL>> eval "$(conda shell.bash hook)" && conda deactivate && conda deactivate && conda deactivate && conda activate base && conda install -y cudnn -c conda-forge
Error while loading conda entry point: conda-libmamba-solver (libarchive.so.19: cannot open shared object file: No such file or directory)

CondaValueError: You have chosen a non-default solver backend (libmamba) but it was not recognized. Choose one of: classic

(base) <<PINOKIO SHELL>> <<PINOKIO SHELL>> eval "$(conda shell.bash hook)" && conda deactivate && conda deactivate && conda deactivate && conda activate base && conda install -y cuda -c nvidia/label/cuda-12.1.0
Error while loading conda entry point: conda-libmamba-solver (libarchive.so.19: cannot open shared object file: No such file or directory)

CondaValueError: You have chosen a non-default solver backend (libmamba) but it was not recognized. Choose one of: classic

(base) <<PINOKIO SHELL>> 
`
Any help / Fix would be apreciated 
Regards

**Comment by lbarasc** [comment]
Same error on Windows 64 bits ! Please help. I want to install Photomaker but i cannot with this error !

**Comment by Hizoka76** [comment]
Same error with v1.2.51.

KDE NEon 64bits

Graphics:
Device-1: NVIDIA 
vendor: Gigabyte 
driver: nvidia v: 545.29.06
Display: x11 
server: X.Org v: 1.21.1.4
NVIDIA GeForce RTX 4070/PCIe/SSE2

Please help

**Comment by Tipez** [comment]
[logs.zip](https://github.com/pinokiocomputer/pinokio/files/14735697/logs.zip)

Please find attached the logs
Regards

**Comment by saschawuest** [comment]
I faced the same problem. 
It is not the correct fix for sure, but as a workaround it was fine for me:
cd ~/pinokio/bin/miniconda
conda config --set solver classic
conda install -n base libarchive -c main --force-reinstall

**Comment by Tipez** [comment]
Wo thanks for the workaround
This works for me !

Some additional steps, 
I have to add conda to ~/.bashrc cause i have the error : "conda command not found" when launching line 2
`nano  ~/.bashrc` and put at the end of the file
`export PATH="/home/username/miniconda/bin:$PATH"` then ctrl X and Y

when i launch `conda config --set solver classic` still got an error
`Error while loading conda entry point: conda-libmamba-solver (libarchive.so.19: cannot open shared object file: No such file or directory)`

I still launch the 3rd line, got an error but then it downloads some stuff
`conda install -n base libarchive -c main --force-reinstall`

Going back on pinokio, launch install, then it works
Thanks a lot @saschawuest

**Comment by Hizoka76** [comment]
Thanks to you
