### ISSUE TITLE
Uanble to launch pinokio on windows  

### ISSUE THREAD

**Issue by Kapil9696** [pinokiocomputer/pinokio#196]
"I ran the EXE file and tried to install Pinocchio, but all I see is a blank, white screen."
Pinocchio - 2.1.14 
Windows - Windows 11

**Comment by mienyussuf** [comment]
same here
after installation the process ends without even showing any windows.
tried to launch the app same issue

**Comment by godsonzhou** [comment]
the installation dir must be english

**Comment by dannykorpan** [comment]
Same issue here. Windows 11 23H2, Version 26100.

**Comment by Kapil9696** [comment]
Please use Pinocchio version 2.0.4 to fix the issue . Mine is working fine

**Comment by dannykorpan** [comment]
Same problem:
```
Ereignisname: APPCRASH
Antwort: Nicht verf�gbar
CAB-Datei-ID: 0

Problemsignatur:
P1: Pinokio.exe
P2: 2.0.4.0
P3: 64dcda3e
P4: StackHash_1b57
P5: 10.0.26100.1301
P6: ede24b56
P7: c0000374
P8: PCH_FF_FROM_ntdll+0x000000000015F5D4
P9: 
P10: 
```

**Comment by Kapil9696** [comment]
I would suggest follow below steps .
Uninstall previous version: Remove any existing software from your Windows system, specifically the previous installation of [Pinokio].
Download and install Pinokio version 2.0.4: Download the attached updated software package 
Run Pinokio once again: Once the installation is finished, run the Pinokio application.
Wait for initialization: Allow the Pinokio to initialize and start up properly, which may take 10-15 minutes.

**Comment by dannykorpan** [comment]
Done, Pinokio starts, but crashes after a few seconds.

<img width="513" alt="grafik" src="https://github.com/user-attachments/assets/acdb6744-5718-4784-87b3-ddb4ea936ca1">

**Comment by KhryptorGraphics** [comment]
Yeah, i have the same issue. Im annoyed.
