### ISSUE TITLE
Fooocus ENOENT: no such file or directory, stat 'C:\pinokio\api\fooocus.git\{{input.event[0]}}'

### ISSUE THREAD

**Issue by Holtzclow** [pinokiocomputer/pinokio#207]
Using cached groundingdino-py-0.4.0.tar.gz (82 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\pinokio\cache\TMPDIR\pip-install-_9gx930e\groundingdino-py_f8cabd7461d54d5b82b6ebaa2a9eebb5\setup.py", line 41, in <module>
          readme = readme_file.read()
      UnicodeDecodeError: 'cp932' codec can't decode byte 0x97 in position 2879: illegal multibyte sequence
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

**Comment by moobond** [comment]
Same problem here.  The last version had no problem.

**Comment by Holtzclow** [comment]
somehow it solve.
1. pip install groundingdino-py-0.4.0.zip
2. pip uninstall groundingdino
3. pip install -r requirements_versions.txt
4. pip uninstall groundingdino-py
5. pip install groundingdino-py-0.4.0.zip
![1](https://github.com/user-attachments/assets/96037f4c-828d-46ee-be8a-2e4e52ea2cf7)
from the file ./groundingdino/util/inference.py import the Model. There is no file called inference.py"
when I check C:\pinokio\api\fooocus.git\app\env\Lib\site-packages
there is inference.py
![2](https://github.com/user-attachments/assets/fc821594-2aec-4c86-a146-17387e1806a0)
and restart pinokio... somehow it works.. (can't explain why)

**Comment by screan** [comment]
same issue here on MacOS

**Comment by moobond** [comment]
> somehow it solve.
> 
> 1. pip install groundingdino-py-0.4.0.zip
> 2. pip uninstall groundingdino
> 3. pip install -r requirements_versions.txt
> 4. pip uninstall groundingdino-py
> 5. pip install groundingdino-py-0.4.0.zip
>    ![1](https://private-user-images.githubusercontent.com/65526708/357058572-96037f4c-828d-46ee-be8a-2e4e52ea2cf7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMzc3MjUsIm5iZiI6MTcyNDMzNzQyNSwicGF0aCI6Ii82NTUyNjcwOC8zNTcwNTg1NzItOTYwMzdmNGMtODI4ZC00NmVlLWJlOGEtMmU0ZTUyZWEyY2Y3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDE0MzcwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0ZjZhYjg3Yzk3YjFhMGU3NjMxYzYwNDE2YjAwNTIxNTRkZjA5ZDBjMjY1ODkyYjJlM2VhZWI5MjljNDE4OTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4OEx7alKVR0HImlct2NTVNdO_o-o2sc7RTPhb6fFnvU)
>    from the file ./groundingdino/util/inference.py import the Model. There is no file called inference.py"
>    when I check C:\pinokio\api\fooocus.git\app\env\Lib\site-packages
>    there is inference.py
>    ![2](https://private-user-images.githubusercontent.com/65526708/357058650-fc821594-2aec-4c86-a146-17387e1806a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMzc3MjUsIm5iZiI6MTcyNDMzNzQyNSwicGF0aCI6Ii82NTUyNjcwOC8zNTcwNTg2NTAtZmM4MjE1OTQtMmFlYy00Yzg2LWExNDYtMTczODdlMTgwNmEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDE0MzcwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhOGQyMTBmMjM1MmRhOTJmODRhMzc2MzIwZGU5ZTg1ZDE1Nzg4YmU0ZjM0Mjg1Y2FkYjcwNmRhZWNjZWM1MWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uaBY_vDRiT-IazBH4M9mY93bF7OX0q03Ph7is8kXUNQ)
>    and restart pinokio... somehow it works.. (can't explain why)

It is too technical.  I do not understand about it.

**Comment by karstenxavier** [comment]
> 1. pip install groundingdino-py-0.4.0.zip

so need to install python to my PC and do this?
