### ISSUE TITLE
Use Pinokio from another Machine

### ISSUE THREAD

**Issue by ManuXD32** [pinokiocomputer/pinokio#238]
Is there a way to install Pinokio on a headless machine and use it from another machine over LAN?
Thanks in advance

**Comment by ManuXD32** [comment]
There's a way, if anyone else in looking for this here's a little guide.
After installing pinokio on the headless machine do this:
1. sudo apt install python3 python3-pip git build-essential libxrender-dev mesa-common-dev xvfb 
2. Xvfb :0 -screen 0 1280x720x24 & 
3. export DISPLAY=:0
4. pinokio

Now you can access pinokio GUI from LAN with the IP of the machine and the port specified on the terminal (which usually is 42000)

**Comment by osering** [comment]
on lubuntu 24.02.2 (as GPU sever) I even did not need to do all the stuff as described in previous post, just:
sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
Nevertheless I cannot beet running headless (i.e. as webserver only). If there is no any options use, running pinokio (over ssh -X), then there is this nice GUI window, which is completely usable, with same content as web@42000, but a bit slow, but when using option --headless, the same GUI window appears, but just as completely white, non functional window, but webserver is running properly. In any case, when this GUI window is closed, web server (demon) also is killed.
Is there some option/key to run it as just plain demon?
