### ISSUE TITLE
"conda_hook" is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by Sculptulator** [pinokiocomputer/pinokio#43]
Hey, I usually try to figure these things out myself, but I thought I'd try the community for once. I am trying to install A1111 and Ooba however I am running into this issue where I cannot install the pre-requests. I've done this manually many times, but I figured pinokio would be an easier one stop solution to all of my AI needs. Help is much appreciated, if I'm doing something dumb, pointing that out is much appreciated as well. Just point me in the right direction and I'll un-dumb myself.

---Thanks in advance---

Issue:
Microsoft Windows [Version 10.0.19045.3570]
(c) Microsoft Corporation. All rights reserved.

C:\Users\User\pinokio\bin>conda_hook && conda activate base && conda install nodejs -y -c conda-forge
'conda_hook' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\User\pinokio\bin>reg add HKLM\SYSTEM\CurrentControlSet\Control\FileSystem /v LongPathsEnabled /t REG_DWORD /d 1 /f
The operation completed successfully.

![image](https://github.com/pinokiocomputer/pinokio/assets/149812249/cf7166dd-ac66-4027-9774-0429d8c12d95)

**Comment by Sculptulator** [comment]
Nevermind, fixed it myself. But to help anyone else who has this issue. Go to windows, type environment. Edit the system environment>Advanced tab> User variables for (username), scroll to the bottom>select path>New>then type C:\Users\(yourusername)\pinokio\bin\miniconda\condabin

Obviously without the parentheses. Adjust the path if you changed your drive, but its in the condabin. 

Thought I pathed it before but turns out I was in the wrong location, oh well. Hopefully this is helpful for someone.

**Comment by jeffhaskin** [comment]
I don't have `condabin` inside pinokio\bin\miniconda`, just `bin`.
