### ISSUE TITLE
trouble installing face fusion in the pinokio ai browser

### ISSUE THREAD

**Issue by philips9179** [pinokiocomputer/pinokio#75]

**Comment by asifbridge** [comment]
ENOENT: no such file or directory, stat 'C:\Users\Asif\pinokio\api\facefusion-pinokio.git\{{input.stdout.match(\(http:\S+)\gi)[0]}}
i am getting this message while trying to lauching facefusion on pinokio browser

**Comment by profplum700** [comment]
Same issue here as OP. Running Windows 11 on Intel Core i7 13th Gen, 16GB RAM and 1TB SSD.
