### ISSUE TITLE
Pinokio browser 2.15.1 (Win32) hangs (white screen) with 'chatbot-ollama.git' installed

### ISSUE THREAD

**Issue by cmackenna** [pinokiocomputer/pinokio#858]
Pinokio browser 2.15.1 (Win32) hangs (white screen) with 'chatbot-ollama.git' installed

Note: Pinokio browser was working fine with chatbot-ollama a few weeks ago.  The only way to get Pinokio browser to stop hanging on startup is to remove the 'chatbot-ollama.git' folder.  After this, a fresh install of 'chatbot-ollama.git' does not correct the problem, and Pinokio browser hangs again (white screen).

After much trial and error I found the hang is caused by 'chatbot-ollama.git/pinokio.js' file.  Specifically, commenting out the following section of code in 'chatbot-ollama.git/pinokio.js' seems to be a workaround:

    // if (kernel.jsdom) {
    //   let JSDOM = kernel.jsdom.JSDOM
    //   let dom = await JSDOM.fromURL("https://ollama.com/library")
    //   let els = dom.window.document.querySelectorAll("#repo li a")
    //   let urls = []
    //   names = []
    //   for(let el of els) {
    //     urls.push(el.href)
    //     names.push(new URL(el.href).pathname.split("/").filter(x => x)[1])
    //   }
    //   console.log("names", names)
    // }

**Comment by cmackenna** [comment]
I realize now what may have caused this problem to surface:  I recently updated the Ollama app from https://ollama.com/
However, updating the Ollama app from https://ollama.com/ should not cause Pinokio browser to hang on startup (white screen), unless I remove 'chatbot-ollama.git' folder, or comment out the section of code above in 'chatbot-ollama.git/pinokio.js' file.

**Comment by Sterling177** [comment]
noticed this tonight.. just hangs - and pinokio is unresponsive. dumped ollama git folder like you said.. guess Ill just run ollama via griptape.

**Comment by cmackenna** [comment]
Open WebUI is an alternative for inferencing llama3.1, etc. inside Pinokio browser, but does require setting up a free account.  Personally, I prefer chatbot-ollama interface because it's developed specifically for use with ollama.com models and provides a 'System Prompt' for putting a model into context for role playing.

**Comment by Sterling177** [comment]
Yeah.. deleting it made comfy comfy again. I use ollama and vision inside comfy ui with grip tape.

**Comment by cmackenna** [comment]
I checked again this evening.  A fresh install of  'chatbot-ollama.git' now works correctly.  Looking at the repository for  'chatbot-ollama.git' nothing has changed.  So, the URL "https://ollama.com/library" must have been causing Pinokio browser to hang on startup (white screen), and the problem with the URL has since been resolved at ollama.com.  Just guessing here.
