### ISSUE TITLE
Trellis Installed fine, but results in an "Error" when generating.

### ISSUE THREAD

**Issue by hansolocambo** [pinokiocomputer/pinokio#869]
Trellis, just installed, gives me that: _Error_ (cf. image thereafter)
![Clipboard Image](https://github.com/user-attachments/assets/9aafafe7-32f1-4008-8611-e57dc7f98c93)

I installed what I thought was necessary: Visual Studio / Desktop Development with C++ / Buildtools LTSC 17.8, CUDA Toolkit 12.4, cudnn 12.6.
Then installed Pinokio for the first time, mainly because I struggled to install Trellis by myself. And damn those 1 click install are a-m-a-zing !  :)  I installed Forge, ComfyUI, and then Trellis. Every setup went fine without a single error. So cool. 
Except for this Trellis error when I try to use it :/ Could someone please take a look at the log attached to this message. Hopefully it'll give an idea of what could cause that?

Windows 11 Pro
RTX 3090 24GB - i9-12900K - 32GB DDR6

[hansolocambo logs 2024-12-21 Trellis Error.zip](https://github.com/user-attachments/files/18216280/hansolocambo.logs.2024-12-21.Trellis.Error.zip).

Thanks!

**Comment by sasaiber** [comment]
same on Laptop rtx 3080 16gb - ryzen 7 5800H - 32 Gb
